using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using SoundCalibrator.Core.Analysis;
using SoundCalibrator.Core.DSP;

namespace SoundCalibrator.Core.Serialization;

public static class DspFilterExporter
{
    public static string ExportMiniDsp(IReadOnlyList<PeqFilterSuggestion> filters, float sampleRate = 48000f)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# miniDSP Biquad Coefficients (Fs = {sampleRate:0} Hz)");
        sb.AppendLine("# Generated by SoundCalibrator");

        for (int i = 0; i < filters.Count; i++)
        {
            var f = filters[i];
            var biquad = BiquadFilter.CreatePeq(f.FrequencyHz, f.GainDb, f.Q, sampleRate);

            // En convención miniDSP:
            // H(z) = (b0 + b1*z^-1 + b2*z^-2) / (1 + a1*z^-1 + a2*z^-2)
            // (a1 y a2 se invierten de signo según el estándar del procesador)
            string line = string.Format(
                CultureInfo.InvariantCulture,
                "biquad{0}={1:0.00000000},{2:0.00000000},{3:0.00000000},{4:0.00000000},{5:0.00000000}",
                i + 1,
                biquad.B0,
                biquad.B1,
                biquad.B2,
                -biquad.A1,
                -biquad.A2);

            sb.AppendLine(line);
        }

        return sb.ToString();
    }

    public static string ExportGenericCsv(IReadOnlyList<PeqFilterSuggestion> filters)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Band,Type,FrequencyHz,GainDb,Q,BandwidthOctaves");

        for (int i = 0; i < filters.Count; i++)
        {
            var f = filters[i];
            string line = string.Format(
                CultureInfo.InvariantCulture,
                "{0},PEQ,{1:0.0},{2:+0.00;-0.00;0.00},{3:0.00},{4:0.00}",
                i + 1,
                f.FrequencyHz,
                f.GainDb,
                f.Q,
                f.BandwidthOctaves);

            sb.AppendLine(line);
        }

        return sb.ToString();
    }
}
